### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by VolodymyrYarosh** [VolodymyrYarosh/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by mamkintester77** [comment]
<h2>Résumé</h2>
                    <p>&mdash; Hello! I’m an engineer<strong style="margin-left: 0.0625em;"></strong> with 10 years of experience in a local TV company. Now I am self-studying and studying on different courses to become a
                    QA engineer.</p>

**Comment by VolodymyrYarosh** [comment]
Thank you very match
