### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by VolodymyrYarosh** [VolodymyrYarosh/homepage#4]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by mamkintester77** [comment]
<section>
                  <h3>LIFE & EDUCATION</h3>
                  <p class="tags small">To live is to fight and to fight is to live. I started learning fighting at my master Gouken's castle, I was beaten at
                  head way too often to remember when exactly.</p>
                </section>
                
                <section>
                  <h3>LANGUAGES</h3>
                  <p class="tags small">
                    <g-emoji class="g-emoji" alias="us"
                      fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f1fa-1f1f8.png">🇺🇸</g-emoji> ENGLISH
                    <g-emoji class="g-emoji" alias="cn"
                      fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f1e8-1f1f3.png">🇨🇳</g-emoji> MANDARIN
                    <g-emoji class="g-emoji" alias="jp"
                      fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f1ef-1f1f5.png">🇯🇵</g-emoji> JAPANESE
                  </p>
                </section>
                
                <section>
                  <h3>Skills</h3>
                  <p class="tags small">KARATE ENERGY ATTACK SHORYUKEN WALKING <span class="nowrap">BAREFOOT</span> PLAYING VIDEOGAMES DOING BURGERS <span class="nowrap">MASHING</span> POTATOES COPYWRITING ACTING
                  VOICEOVERS</p>
                </section>
                
                <section>
                  <h3>Character</h3>
                  <p class="tags small">NOBLE DIRECT BOLD CONFIDENT DARING SCHIZOPHRENIC DRAMATIC PERSUASIVE IMMEDIATE WISE</p>
                </section>
                
                <section>
                  <h3>LIFE LESSON</h3>
                  <p class="tags small">You must defeat Sheng Long to stand a chance.</p>
                </section>
                
                <section>
                  <h3>Likes&#x1f603;</h3>
                  <p class="tags small">GI VEGETABLES BLOOD SMALL MARSHMELLOWS RED COLOR KILLED ENEMY</p>
                </section>
                
                <section>
                  <h3>Dislikes&#x1f61e;</h3>
                  <p class="tags small">BISONS GHOSTS SMARTPHONES SMELL OF SEAFOOD BARBER SHOPS SLEEVES</p>
                </section>
                
                <section>
                  <h3>Wants&#x1f97a;</h3>
                  <p class="tags small bulleted">BE FIT WRITE MORE BOOKS FIND A GIRLFRIEND TO GO TO CINEMA WITH KILL ALL OF AKUMA FAMILY</p>
                </section>

**Comment by VolodymyrYarosh** [comment]
thank you
