### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by VolodymyrYarosh** [VolodymyrYarosh/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by mamkintester77** [comment]
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis.

**Comment by VolodymyrYarosh** [comment]
thank you very much
