### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by VolodymyrYarosh** [VolodymyrYarosh/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by mamkintester77** [comment]
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis.

**Comment by VolodymyrYarosh** [comment]
thank you very much
