### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by VolodymyrYarosh** [VolodymyrYarosh/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by mamkintester77** [comment]
<h3>Experience</h3>
                <h6>Recent</h6>
                
                <ul class="timeline">
                  
                  <li>
                    <p><em>2018</em></p>
                    <p>Amongst many fighters of the past was featured in the movie <strong>"Ready Player One"</strong>. Ryu ready always!</p>
                  </li>
                  <li>
                    <p><em>2017</em></p>
                    <p>United with unknown until then to me <strong>Power Rangers</strong> to defea resurrected <strong>M.Bison.Damn</strong> good fighters they are, even not
                    knowing karate ways!</p>
                  </li>
                  <li>
                    <p><em>2016</em></p>
                    <p>In <strong>"Street Fighter V"</strong> once and for all erased M.Bison from earth and tamed my inner Evil Ryu. Also spent some time on a
                    side-project, mini-series "Street Fighter: Resurrection".</p>
                  </li>
                  <li>
                    <p><em>2014</em></p>
                    <p>Filmed in a martial arts tutorial <strong>"Street Fighter: Assassin's Fist"</strong>"Street Fighter: Assassin's Fist", revealing to audience forgotten art of Ansatsuken.</p>
                  </li>
                  <li>
                    <p><em>2012</em></p>
                    <p><strong></strong>The gods of intenet concluded me in the animated movie <strong>"Wreck-It Ralph"</strong>, but rewarded me with a good drink for it!</p>
                  </li>
                  <li>
                    <p><em>2008</em></p>
                    <p>My evil alter ego sneaked out of control and became a boss in <strong>"Street Fighter IV"</strong>.</p>
                  </li>
                  <li>
                    <p><em>2006</em></p>
                    <p>Borrowed my famous ripped gi to Soki in <strong>"Onimusha: Dawn of Dreams"</strong>, gods informed me he needed that for the battle.</p>
                  </li>
                  <li>
                    <p><em>1998</em></p>
                    <p>Defeated M. Bison in <strong>"Street Fighter Alpha 2"</strong>, bastard wanted to use my heroic body for his evil intentions, but
                    retreated with shame. Also this year I encountered Marvel universe in <strong>"Marvel vs. Capcom: Clash of Super Heroes"</strong>
                    fighter, loyal to my employer, Capcom, of course.</p>
                  </li>
                  <li>
                    <p><em>1997</em></p>
                    <p>Reunited with Ken, my friend and opponent in <strong>"Street Fighter III"</strong>. Men's friendship works mysteriously. Also helped with
                    Arika project <strong>"Street Fighter EX"</strong>.</p>
                  </li>
                  <li>
                    <p><em>1996</em></p>
                    <p>Took care of villainous Akuma in <strong>"Street Fighter Alpha 2"</strong>. As a freelance on <strong>"Super Puzzle Fighter II Turbo"</strong>"Super Puzzle Fighter II Turbo" tried
                    myself in a new genre, puzzle games. Let the wrath of seven heavens come upon these malicious enigmas, never again!</p>
                  </li>
                  <li>
                    <p><em>1995</em></p>
                    <p>Kept fighting in <strong>"Street Fighter Alpha: Warriors' Dreams"</strong>.</p>
                  </li>
                  <li>
                    <p><em>1994</em></p>
                    <p>Screened in a movie <strong>"Street Fighter"</strong>, so that the batllesof past would not be forgotten by millenial generation.</p>
                  </li>
                  <li>
                    <p><em>1991</em></p>
                    <p>Was promoted to <strong>"Street Fighter II"</strong>. Didn't stay there for long, celebrations and office dwelling is not for me!</p>
                  </li>
                  <li>
                    <p><em>1987</em></p>
                    <p>Started working for Capcom project <strong>"Street Fighter"</strong>. My partner was Ken Masters, the boss'name was Sagat.</p>
                  </li>
                </ul>
                
                <h3>PUBLICATIONS</h3>
                <ul class="timeline">
                  <li>
                    <p><em>2011</em></p>
                    <p>The true and humble story of me under pseudonim Tyler Wilde in an article "The evolution of Ken
                      and Ryu".</p>
                  </li>
                  <li>
                    <p><em>2003 &ndash; 2018</em></p>
                    <p>For 15 years I have published comic books with Udon Entertainment depicting my adventures,
                    bitter lessons and great victories.</p>
                  </li>
                </ul>
                
                <h3>ACHIEVEMENTS</h3>
                <ul>
                  <li>#1 in "Top 25 Street Fighter Characters" by IGN, who also called me "fancy", "icon" and "a testament to the virtue of simplicity" <g-emoji class="g-emoji" alias="heart" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/2764.png">❤️</g-emoji></li>
                  <li>#2 in "Top 20 Street Fighter Characters of All Time" by GameDaily, same council found me worth of #6 place in "Top 25 Capcom Characters of All Time", which I proudly share with my partner Ken</li>
                  <li>I was named "5th Most Powerful Street Fighter Character" by Screen Rant-san</li>
                  <li>#71 in "Top 100 Heroes of All Time" by UGO Networks, also recognized #2 in their list of "Top 50 Street Fighter Characters"</li>
                  <li>In a survey of 4000 online matches for Super Street Fighter IV, I got to be the most popular character, with 16.6% of players choosing my side</li>
                </ul>

**Comment by VolodymyrYarosh** [comment]
thank you
