### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by VolodymyrYarosh** [VolodymyrYarosh/homepage#7]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by mamkintester77** [comment]
<div class="avatar-wrapper">
                  <object class="avatar" data="https://scontent.flwo4-2.fna.fbcdn.net/v/t1.6435-9/175816056_1488476207989330_6672049610769173594_n.jpg?_nc_cat=102&ccb=1-3&_nc_sid=09cbfe&_nc_ohc=yYrkMEuXM10AX9wvsPH&_nc_ht=scontent.flwo4-2.fna&oh=10b8c6fad74556beccbd7d924f5c37e7&oe=60B4E48E" role="img" aria-label="My profile picture"></object>
                </div>
 
                    <h2>Résumé</h2>
                    <p>&mdash; I do not compete with others, the only competition that challenges me is myself. As a fighter, friend and an employee
                    I am known as contemplative, tortured and driven.</p>

**Comment by VolodymyrYarosh** [comment]
thank you
